# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/boncz/fsst

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/boncz/fsst

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/boncz/fsst/CMakeFiles /Users/boncz/fsst//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/boncz/fsst/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named binary

# Build rule for target.
binary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary
.PHONY : binary

# fast build rule for target.
binary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/build
.PHONY : binary/fast

#=============================================================================
# Target rules for targets named fsst

# Build rule for target.
fsst: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsst
.PHONY : fsst

# fast build rule for target.
fsst/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fsst.dir/build.make CMakeFiles/fsst.dir/build
.PHONY : fsst/fast

fsst.o: fsst.cpp.o

.PHONY : fsst.o

# target to build an object file
fsst.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/fsst.cpp.o
.PHONY : fsst.cpp.o

fsst.i: fsst.cpp.i

.PHONY : fsst.i

# target to preprocess a source file
fsst.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/fsst.cpp.i
.PHONY : fsst.cpp.i

fsst.s: fsst.cpp.s

.PHONY : fsst.s

# target to generate assembly for a file
fsst.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary.dir/build.make CMakeFiles/binary.dir/fsst.cpp.s
.PHONY : fsst.cpp.s

fsst_avx512.o: fsst_avx512.cpp.o

.PHONY : fsst_avx512.o

# target to build an object file
fsst_avx512.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fsst.dir/build.make CMakeFiles/fsst.dir/fsst_avx512.cpp.o
.PHONY : fsst_avx512.cpp.o

fsst_avx512.i: fsst_avx512.cpp.i

.PHONY : fsst_avx512.i

# target to preprocess a source file
fsst_avx512.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fsst.dir/build.make CMakeFiles/fsst.dir/fsst_avx512.cpp.i
.PHONY : fsst_avx512.cpp.i

fsst_avx512.s: fsst_avx512.cpp.s

.PHONY : fsst_avx512.s

# target to generate assembly for a file
fsst_avx512.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fsst.dir/build.make CMakeFiles/fsst.dir/fsst_avx512.cpp.s
.PHONY : fsst_avx512.cpp.s

libfsst.o: libfsst.cpp.o

.PHONY : libfsst.o

# target to build an object file
libfsst.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fsst.dir/build.make CMakeFiles/fsst.dir/libfsst.cpp.o
.PHONY : libfsst.cpp.o

libfsst.i: libfsst.cpp.i

.PHONY : libfsst.i

# target to preprocess a source file
libfsst.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fsst.dir/build.make CMakeFiles/fsst.dir/libfsst.cpp.i
.PHONY : libfsst.cpp.i

libfsst.s: libfsst.cpp.s

.PHONY : libfsst.s

# target to generate assembly for a file
libfsst.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fsst.dir/build.make CMakeFiles/fsst.dir/libfsst.cpp.s
.PHONY : libfsst.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... binary"
	@echo "... fsst"
	@echo "... fsst.o"
	@echo "... fsst.i"
	@echo "... fsst.s"
	@echo "... fsst_avx512.o"
	@echo "... fsst_avx512.i"
	@echo "... fsst_avx512.s"
	@echo "... libfsst.o"
	@echo "... libfsst.i"
	@echo "... libfsst.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

